services:
  - type: web
    name: perla
    plan: free
    runtime: python
    buildCommand: ./build.sh
    startCommand: uvicorn perla.asgi:application --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: perladb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

