databases:
  - name: perladb
    plan: free
    databaseName: perla
    user: perla

services:
  - type: web
    plan: free
    name: perla
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn perla.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: perladb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4