services:
  - type: web
    name: perla
    plan: free
    runtime: python
    buildCommand: ./build.sh
    startCommand: python -m gunicorn perla.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: perladb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
